[build-system]
requires = ["uv_build >= 0.9.21, <0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["tealogger"]
module-root = ""
source-include = [
  "configuration/*",
]

[project]
name = "tealogger"
version = "0.9.1"
description = "Tea Logger"
keywords = ["tealogger"]
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
requires-python = ">= 3.11"

classifiers = [
  "Development Status :: 3 - Alpha",

  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",

  "License :: OSI Approved :: MIT License",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

authors = [ {name = "TeaFTI"} ]

dependencies = []

[dependency-groups]
develop = [
  "build",
  "pytest-cov",
  "pytest",
  "ruff",
  "ty"
]
test = [
  "pytest>=9.0",
  "pytest-cov",
  "pytest-mock",
  "tox",
]

[project.urls]
"Homepage" = "https://github.com/TeaFTI/Python-TeaLogger"
Repository = "https://github.com/TeaFTI/Python-TeaLogger"
"Bug Tracker" = "https://github.com/TeaFTI/Python-TeaLogger/issues"
